# Generated by Django 5.1.3 on 2025-11-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('pppoker_id', models.CharField(blank=True, default='', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('club_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['telegram_id'], name='users_telegra_d76140_idx'), models.Index(fields=['synced_to_sheets'], name='users_synced__ad6876_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpinUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_spins', models.IntegerField(default=0)),
                ('total_spins_used', models.IntegerField(default=0)),
                ('total_chips_earned', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spin_data', to='api.user')),
            ],
            options={
                'db_table': 'spin_users',
                'indexes': [models.Index(fields=['user'], name='spin_users_user_id_2e1e7c_idx'), models.Index(fields=['synced_to_sheets'], name='spin_users_synced__86a466_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=100)),
                ('chips', models.IntegerField()),
                ('pppoker_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Auto', 'Auto')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_history', to='api.user')),
            ],
            options={
                'db_table': 'spin_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='spin_histor_user_id_53153c_idx'), models.Index(fields=['status', 'created_at'], name='spin_histor_status_39eb59_idx'), models.Index(fields=['synced_to_sheets'], name='spin_histor_synced__6ecfa6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('proof_image_path', models.CharField(max_length=500)),
                ('pppoker_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='api.user')),
            ],
            options={
                'db_table': 'deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='deposits_user_id_a42880_idx'), models.Index(fields=['status', 'created_at'], name='deposits_status_564167_idx'), models.Index(fields=['synced_to_sheets'], name='deposits_synced__26e957_idx')],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('pppoker_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='api.user')),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='withdrawals_user_id_38a9fa_idx'), models.Index(fields=['status', 'created_at'], name='withdrawals_status_7d3043_idx'), models.Index(fields=['synced_to_sheets'], name='withdrawals_synced__2a4799_idx')],
            },
        ),
    ]
