# Generated by Django 5.1.3 on 2025-11-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField()),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'counter_status',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(default='Admin', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admins',
                'indexes': [models.Index(fields=['telegram_id'], name='admins_telegra_907728_idx'), models.Index(fields=['is_active'], name='admins_is_acti_5d7c65_idx'), models.Index(fields=['synced_to_sheets'], name='admins_synced__c82302_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT_TRC20', 'USDT TRC20'), ('USDT_BEP20', 'USDT BEP20'), ('BankTransfer', 'Bank Transfer')], max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payment_accounts',
                'indexes': [models.Index(fields=['method', 'is_active'], name='payment_acc_method_09070c_idx'), models.Index(fields=['synced_to_sheets'], name='payment_acc_synced__623b2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'promo_codes',
                'indexes': [models.Index(fields=['code'], name='promo_codes_code_5b1d05_idx'), models.Index(fields=['is_active'], name='promo_codes_is_acti_856e08_idx'), models.Index(fields=['start_date', 'end_date'], name='promo_codes_start_d_f6c450_idx'), models.Index(fields=['synced_to_sheets'], name='promo_codes_synced__21c175_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cashback_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cashback_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pppoker_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_requests', to='api.user')),
            ],
            options={
                'db_table': 'cashback_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cashback_re_user_id_9a5a29_idx'), models.Index(fields=['status', 'created_at'], name='cashback_re_status_c3b191_idx'), models.Index(fields=['week_start', 'week_end'], name='cashback_re_week_st_c65b1e_idx'), models.Index(fields=['synced_to_sheets'], name='cashback_re_synced__86b5c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pppoker_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.user')),
            ],
            options={
                'db_table': 'join_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='join_reques_user_id_d1f7fe_idx'), models.Index(fields=['status', 'created_at'], name='join_reques_status_7c3763_idx'), models.Index(fields=['synced_to_sheets'], name='join_reques_synced__efeded_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('slip_image_path', models.CharField(max_length=500)),
                ('pppoker_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests', to='api.user')),
            ],
            options={
                'db_table': 'seat_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='seat_reques_user_id_58bd8d_idx'), models.Index(fields=['status', 'created_at'], name='seat_reques_status_051704_idx'), models.Index(fields=['synced_to_sheets'], name='seat_reques_synced__c4af10_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_from_user', models.BooleanField(default=True)),
                ('replied_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='api.user')),
            ],
            options={
                'db_table': 'support_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='support_mes_user_id_d84a67_idx'), models.Index(fields=['synced_to_sheets'], name='support_mes_synced__59aebb_idx')],
            },
        ),
    ]
