# Generated by Django 5.1.3 on 2025-11-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_counterstatus_admin_paymentaccount_promocode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=10)),
                ('currency_to', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'exchange_rates',
                'indexes': [models.Index(fields=['currency_from', 'currency_to', 'is_active'], name='exchange_ra_currenc_9d4c60_idx'), models.Index(fields=['synced_to_sheets'], name='exchange_ra_synced__42b253_idx')],
                'unique_together': {('currency_from', 'currency_to')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove'), ('Adjustment', 'Adjustment')], max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField()),
                ('synced_to_sheets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_name', 'created_at'], name='inventory_t_item_na_eebcee_idx'), models.Index(fields=['transaction_type'], name='inventory_t_transac_a372b6_idx'), models.Index(fields=['synced_to_sheets'], name='inventory_t_synced__ecc465_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_balances', to='api.user')),
            ],
            options={
                'db_table': 'club_balances',
                'indexes': [models.Index(fields=['user'], name='club_balanc_user_id_bd7965_idx'), models.Index(fields=['synced_to_sheets'], name='club_balanc_synced__6c1bd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FiftyFiftyInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loss_share', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='api.user')),
            ],
            options={
                'db_table': 'fifty_fifty_investments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='fifty_fifty_user_id_14ce63_idx'), models.Index(fields=['start_date', 'end_date'], name='fifty_fifty_start_d_eb0cc8_idx'), models.Index(fields=['synced_to_sheets'], name='fifty_fifty_synced__a970df_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField()),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='api.user')),
            ],
            options={
                'db_table': 'user_credits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_credit_user_id_bdf6bf_idx'), models.Index(fields=['synced_to_sheets'], name='user_credit_synced__344811_idx')],
            },
        ),
    ]
