# Generated by Django 5.2.5 on 2025-11-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exchangerate_inventorytransaction_clubbalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cashback_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('cashback_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_records', to='api.cashbackrequest')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_recipients', to='api.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_eligibility', to='api.user')),
            ],
            options={
                'db_table': 'cashback_eligibility',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'promotion'], name='cashback_el_user_id_5b8439_idx'), models.Index(fields=['received_at'], name='cashback_el_receive_c7fe6f_idx'), models.Index(fields=['synced_to_sheets'], name='cashback_el_synced__f5685c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromotionEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_records', to='api.deposit')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_recipients', to='api.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_eligibility', to='api.user')),
            ],
            options={
                'db_table': 'promotion_eligibility',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'promotion'], name='promotion_e_user_id_6e231e_idx'), models.Index(fields=['received_at'], name='promotion_e_receive_250c2c_idx'), models.Index(fields=['synced_to_sheets'], name='promotion_e_synced__c9124c_idx')],
            },
        ),
    ]
