# Generated by Django 5.2.5 on 2025-11-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cashbackeligibility_promotioneligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promo_type',
            field=models.CharField(choices=[('bonus', 'Deposit Bonus'), ('cashback', 'Cashback')], default='bonus', max_length=20),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['promo_type', 'is_active'], name='promo_codes_promo_t_51b21a_idx'),
        ),
    ]
