# Generated by Django 5.2.5 on 2025-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_promo_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='method',
            field=models.CharField(choices=[('BML', 'Bank of Maldives'), ('MIB', 'Maldives Islamic Bank'), ('USD', 'USD Cash'), ('USDT', 'USDT Crypto'), ('BTC', 'Bitcoin'), ('USDT_TRC20', 'USDT TRC20'), ('USDT_BEP20', 'USDT BEP20'), ('BankTransfer', 'Bank Transfer')], max_length=50, unique=True),
        ),
    ]
