# Generated by Django 5.2.5 on 2025-11-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_paymentaccount_method'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fiftyfiftyinvestment',
            name='fifty_fifty_user_id_14ce63_idx',
        ),
        migrations.AddField(
            model_name='fiftyfiftyinvestment',
            name='pppoker_id',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='fiftyfiftyinvestment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Lost', 'Lost')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiftyfiftyinvestment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='fiftyfiftyinvestment',
            index=models.Index(fields=['pppoker_id', 'status'], name='fifty_fifty_pppoker_10748d_idx'),
        ),
        migrations.AddIndex(
            model_name='fiftyfiftyinvestment',
            index=models.Index(fields=['status'], name='fifty_fifty_status_a5fed5_idx'),
        ),
    ]
