# Generated by Django 5.2.5 on 2025-12-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_pppoker_id_to_investments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spins_awarded', models.IntegerField()),
                ('source', models.CharField(choices=[('deposit_bonus', 'Deposit Bonus'), ('promotion', 'Promotion'), ('admin_grant', 'Admin Grant'), ('compensation', 'Compensation')], default='deposit_bonus', max_length=20)),
                ('amount_mvr', models.DecimalField(decimal_places=2, help_text='Deposit amount in MVR that triggered the award', max_digits=15)),
                ('awarded_by', models.BigIntegerField(blank=True, help_text='Admin who approved the deposit/granted spins', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_awards', to='api.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_awards', to='api.user')),
            ],
            options={
                'db_table': 'spin_awards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=100)),
                ('chips_won', models.IntegerField()),
                ('pppoker_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('spin_award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='api.spinaward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_usages', to='api.user')),
            ],
            options={
                'db_table': 'spin_usages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='spinaward',
            index=models.Index(fields=['user', 'created_at'], name='spin_awards_user_id_92a493_idx'),
        ),
        migrations.AddIndex(
            model_name='spinaward',
            index=models.Index(fields=['deposit'], name='spin_awards_deposit_1c165b_idx'),
        ),
        migrations.AddIndex(
            model_name='spinaward',
            index=models.Index(fields=['source', 'created_at'], name='spin_awards_source_77365a_idx'),
        ),
        migrations.AddIndex(
            model_name='spinaward',
            index=models.Index(fields=['synced_to_sheets'], name='spin_awards_synced__ea727f_idx'),
        ),
        migrations.AddIndex(
            model_name='spinusage',
            index=models.Index(fields=['user', 'created_at'], name='spin_usages_user_id_055d87_idx'),
        ),
        migrations.AddIndex(
            model_name='spinusage',
            index=models.Index(fields=['spin_award'], name='spin_usages_spin_aw_b935f5_idx'),
        ),
        migrations.AddIndex(
            model_name='spinusage',
            index=models.Index(fields=['synced_to_sheets'], name='spin_usages_synced__85c030_idx'),
        ),
    ]
