# Generated by Django 5.2.5 on 2025-12-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_spinaward_spinusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinuser',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
