# Generated by Django 5.2.5 on 2025-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_spinuser_total_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='slip_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
