# Generated by Django 5.2.5 on 2025-12-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_seatrequest_slip_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
