# Generated by Django 5.2.5 on 2025-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_seatrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatrequest',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='sender_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
