# Generated by Django 5.2.5 on 2025-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_seatrequest_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
    ]
