# Generated by Django 5.2.5 on 2025-12-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_reminder_count_to_usercredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackrequest',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_requests', to='api.promocode'),
        ),
    ]
