# Generated by Django 5.2.5 on 2025-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_promotion_to_cashback_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='proof_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
