# Generated by Django 5.2.5 on 2025-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_make_deposit_proof_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinhistory',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
