# Generated by Django 5.2.5 on 2025-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_notified_at_to_spinhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deposit', 'Deposit Request'), ('spin_reward', 'Spin Reward'), ('withdrawal', 'Withdrawal Request'), ('seat_request', 'Seat Request')], max_length=20)),
                ('notification_key', models.CharField(db_index=True, max_length=255)),
                ('admin_telegram_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_messages',
                'indexes': [models.Index(fields=['notification_key'], name='notificatio_notific_ecf9b7_idx'), models.Index(fields=['notification_type', 'notification_key'], name='notificatio_notific_854944_idx'), models.Index(fields=['admin_telegram_id'], name='notificatio_admin_t_c4dde9_idx')],
                'unique_together': {('admin_telegram_id', 'message_id')},
            },
        ),
    ]
