# Generated by Django 5.2.5 on 2025-12-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notificationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
